version: "3.3"
services:
  frontend:
    build: frontend
    container_name: angular-fr
    ports:
      - 4200:80
    networks:
      - frontend
  backend:
    build: backend
    container_name: node-express-bk
    ports:
      - 3000:3000
    networks:
      - backend
      - frontend

networks:
  frontend:
  backend:
